services:
  dbmysql:
    image: mysql:8.0
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flaskdb
    ports:
      - "3307:3306"
    networks:
      - app-networks

#changed port to 5050. mac was having trouble using 5000
  flask_api:
    build: ./api-python
    container_name: flask_api
    ports:
      - "5050:5050"
    volumes:
      - "./api-python:/app"
    command: "python app.py"
    depends_on:
      - "dbmysql"
    networks:
      - app-networks

  node_api:
    build: ./api-node
    container_name: api-node
    ports:
      - "3001:3001"
    volumes:
      - "./api-node:/app"
      - "/app/node_modules"
    depends_on:
      - "flask_api"
    networks:
      - app-networks

  php-app:
    build: ./api-php
    container_name: php_app
    ports:
      - "8000:3003"
    volumes:
      - ./api-php:/app
    working_dir: /app
    command: php -S 0.0.0.0:3003
    networks:
      - app-networks


networks:
  app-networks:
    driver: bridge