services:
  dbmysql:
    image: mysql:8.0
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flaskdb
    ports:
      - "3307:3306"
    networks:
      - app-networks

  flask_api:
    build: ./python-api
    container_name: flask_api
    ports:
      - "5000:5000"
    volumes:
      - "./python-api:/app"
    command: "python app.py"
    depends_on:
      - "dbmysql"
    networks:
      - app-networks

  node_api:
    build: ./node-api
    container_name: node_api
    ports:
      - "3000:3000"
    volumes:
      - "./node-api:/app"
      - "/app/node_modules"
    depends_on:
      - "flask_api"
    networks:
      - app-networks

  php-app:
    build: ./php
    container_name: php_app
    ports:
      - "8000:8000"
    volumes:
      - ./php:/app
    working_dir: /app
    command: php -S 0.0.0.0:8000
    networks:
      - app-networks


networks:
  app-networks:
    driver: bridge